name: Build and deploy Node.js app to Azure Web App - eureka-movies-fe

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js version (20.x)
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build the React app
      - name: npm install, build
        run: |
          CI=false npm install
          CI=false npm run build --if-present

      # Create a ZIP artifact for deployment
      - name: Zip artifact for deployment
        run: zip -r release.zip ./build # Specify build directory to zip

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eureka-movies-fe'
          slot-name: 'Production'
          package: ./build # Deploy the 'build' folder directly to Azure Web App
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4825B83C8EFC40E189E45602E926AFBB }}

